Insert Into Maps (Id, Name) Values
(0, 'Azeroth'),
(1, 'Outland'),
(2, 'WoD'),
(3, 'Bfa');

Insert Into Expansions (Id, MapId, Name) Values
(1, 0, 'Vanilla'),
(2, 1, 'TBC'),
(3, 0,'WotLK'),
(4, 2, 'WoD'),
(5, 3, 'BfA');

Insert Into Zones (ExpansionId, Name) Values
-- Classic only
(1, 'Alterac Mountains'),
(1, 'Hyjal'),
(1, 'Orgrimmar'),
(1, 'The Barrens'),
(1, 'The Hinterlands'),
(1, 'Thunder Bluff'),
(1, 'Zul''Gurub'),
-- Retail and Mixed classic/retail
(1, 'Abyssal Depths'),
(1, 'Ashenvale'),
(1, 'Arathi Highlands'),
(1, 'Azshara'),
(1, 'Azsuna'),
(1, 'Azuremyst Isle'),
(1, 'Badlands'),
(1, 'Blackrock Mountain'),
(1, 'Blasted Lands'),
(1, 'Bloodmyst Isle'),
(1, 'Burning Steppes'),
(1, 'Cape of Stranglethorn'),
(1, 'Darkshore'),
(1, 'Darnassus'),
(1, 'Deadwind Pass'),
(1, 'Desolace'),
(1, 'Dread Wastes'),
(1, 'Dun Morogh'),
(1, 'Durotar'),
(1, 'Duskwood'),
(1, 'Dustwallow Marsh'),
(1, 'Eastern Plaguelands'),
(1, 'Elwynn Forest'),
(1, 'Eversong Woods'),
(1, 'Felwood'),
(1, 'Feralas'),
(1, 'Ghostlands'),
(1, 'Gilneas'),
(1, 'Highmountain'),
(1, 'Hillsbrad Foothills'),
(1, 'Hinterlands'),
(1, 'Ironforge'),
(1, 'Isle of Quel''danas'),
(1, 'Isle of Thunder'),
(1, 'Jade Forest'),
(1, 'Kelp''thar Forest'),
(1, 'Kezan'),
(1, 'Krasarang Wilds'),
(1, 'Kun-Lai Summit'),
(1, 'Loch Modan'),
(1, 'Maelstrom'),
(1, 'Moonglade'),
(1, 'Mount Hyjal'),
(1, 'Mulgore'),
(1, 'Northern Barrens'),
(1, 'Northern Stranglethorn'),
(1, 'Redridge Mountains'),
(1, 'Searing Gorge'),
(1, 'Shimmering Expanse'),
(1, 'Silithus'),
(1, 'Silvermoon City'),
(1, 'Silverpine Forest'),
(1, 'Southern Barrens'),
(1, 'Stonetalon Mountains'),
(1, 'Stormheim'),
(1, 'Stormwind City'),
(1, 'Stranglethorn Vale'),
(1, 'Swamp of Sorrows'),
(1, 'Suramar'),
(1, 'Tanaris'),
(1, 'Teldrassil'),
(1, 'The Broken Isles'),
(1, 'The Broken Shore'),
(1, 'The Lost Isles'),
(1, 'The Scarlet Enclave'),
(1, 'The Wandering Isle'),
(1, 'The Veiled Stair'),
(1, 'Thousand Needles'),
(1, 'Timeless Isle'),
(1, 'Tirisfal Glades'),
(1, 'Tol Barad'),
(1, 'Townlong Steppes'),
(1, 'Twilight Highlands'),
(1, 'Wetlands'),
(1, 'Western Plaguelands'),
(1, 'Westfall'),
(1, 'Winterspring'),
(1, 'Uldum'),
(1, 'Un''goro Crater'),
(1, 'Vale of Eternal Blossoms'),
(1, 'Valley of the Four Winds'),
(1, 'Val''sharah'),
-- TBC
(2, 'Blade''s Edge Mountains'),
(2, 'Hellfire Peninsula'),
(2, 'Nagrand'),
(2, 'Netherstorm'),
(2, 'Shadowmoon Valley'),
(2, 'Shattrath City'),
(2, 'Terokkar Forest'),
(2, 'Zangarmarsh'),
-- WotLK, though later expansions may have changed some of Northrend https://www.wowhead.com/zones/northrend
(3, 'Borean Tundra'),-- BfA
(3, 'Crystalsong Forest'),
(3, 'Dalaran'),-- Legion
(3, 'Dragonblight'),-- BfA
(3, 'Grizzly Hills'),
(3, 'Howling Fjord'),
(3, 'Icecrown'),-- BfA
(3, 'Sholazar Basin'),-- BfA
(3, 'Storm Peaks'),
(3, 'Wintergrasp'),
(3, 'Zul''drak'),
-- WoD
(4, 'Ashran'),
(4, 'Frostfire Ridge'),
(4, 'Gorgrond'),
(4, 'Nagrand'),
(4, 'Shadowmoon Valley'),
(4, 'Spires of Arak'),
(4, 'Talador'),
(4, 'Tanaan Jungle'),
-- BfA
(5, 'Boralus'),
(5, 'Dazar''Alor'),
(5, 'Drustvar'),
(5, 'Mechagon'),
(5, 'Nazjatar'),
(5, 'Nazmir'),
(5, 'Stormsong Valley'),
(5, 'Tiragarde Sound'),
(5, 'Vol''dun'),
(5, 'Zuldazar');
