Insert Into Maps (Id, Name) Values
(0, 'Azeroth'),
(1, 'Outland'),
(2, 'WoD'),
(3, 'Bfa');

Insert Into Expansions (Id, MapId, Name) Values
(1, 0, 'Vanilla'),
(2, 1, 'TBC'),
(3, 0, 'WotLK'),
(4, 0, 'Cata'),
(5, 2, 'WoD'),
(6, 3, 'BfA');

Insert Into Zones (ExpansionId, Name) Values
-- Vanila only
(1, 'Alterac Mountains'),
(1, 'Hyjal'),
(1, 'Orgrimmar'),
(1, 'The Barrens'),
(1, 'The Hinterlands'),
(1, 'Thunder Bluff'),
(1, 'Zul''Gurub'),
-- Mixed Vanilla/Cata
(1, 'Ashenvale'),
(1, 'Arathi Highlands'),
(1, 'Azshara'),
(1, 'Badlands'),
(1, 'Blasted Lands'),
(1, 'Burning Steppes'),
(1, 'Darkshore'),
(1, 'Darnassus'),
(1, 'Deadwind Pass'),
(1, 'Desolace'),
(1, 'Dun Morogh'),
(1, 'Durotar'),
(1, 'Duskwood'),
(1, 'Dustwallow Marsh'),
(1, 'Eastern Plaguelands'),
(1, 'Elwynn Forest'),
(1, 'Felwood'),
(1, 'Feralas'),
(1, 'Hillsbrad Foothills'),
(1, 'Loch Modan'),
(1, 'Moonglade'),
(1, 'Mulgore'),
(1, 'Redridge Mountains'),
(1, 'Searing Gorge'),
(1, 'Silithus'),
(1, 'Silverpine Forest'),
(1, 'Stonetalon Mountains'),
(1, 'Stormwind City'),
(1, 'Stranglethorn Vale'),
(1, 'Swamp of Sorrows'),
(1, 'Tanaris'),
(1, 'Teldrassil'),
(1, 'Thousand Needles'),
(1, 'Tirisfal Glades'),
(1, 'Wetlands'),
(1, 'Western Plaguelands'),
(1, 'Westfall'),
(1, 'Winterspring'),
(1, 'Un''goro Crater'),
-- TBC
(2, 'Blade''s Edge Mountains'),
(2, 'Hellfire Peninsula'),
(2, 'Nagrand'),
(2, 'Netherstorm'),
(2, 'Shadowmoon Valley'),
(2, 'Shattrath City'),
(2, 'Terokkar Forest'),
(2, 'Zangarmarsh'),
-- WotLK, though later expansions may have changed some of Northrend https://www.wowhead.com/zones/northrend
(3, 'Borean Tundra'),-- BfA
(3, 'Crystalsong Forest'),
(3, 'Dalaran'),-- Legion
(3, 'Dragonblight'),-- BfA
(3, 'Grizzly Hills'),
(3, 'Howling Fjord'),
(3, 'Icecrown'),-- BfA
(3, 'Sholazar Basin'),-- BfA
(3, 'Storm Peaks'),
(3, 'Wintergrasp'),
(3, 'Zul''drak'),
-- Cata only
(4, 'Abyssal Depths'),
(4, 'Azsuna'),
(4, 'Azuremyst Isle'),
(4, 'Blackrock Mountain'),
(4, 'Bloodmyst Isle'),
(4, 'Cape of Stranglethorn'),
(4, 'Dread Wastes'),
(4, 'Eversong Woods'),
(4, 'Ghostlands'),
(4, 'Gilneas'),
(4, 'Highmountain'),
(4, 'Hinterlands'),
(4, 'Ironforge'),
(4, 'Isle of Quel''danas'),
(4, 'Isle of Thunder'),
(4, 'Jade Forest'),
(4, 'Kelp''thar Forest'),
(4, 'Kezan'),
(4, 'Krasarang Wilds'),
(4, 'Kun-Lai Summit'),
(4, 'Maelstrom'),
(4, 'Mount Hyjal'),
(4, 'Northern Barrens'),
(4, 'Northern Stranglethorn'),
(4, 'Shimmering Expanse'),
(4, 'Silvermoon City'),
(4, 'Southern Barrens'),
(4, 'Stormheim'),
(4, 'Suramar'),
(4, 'The Broken Isles'),
(4, 'The Broken Shore'),
(4, 'The Lost Isles'),
(4, 'The Scarlet Enclave'),
(4, 'The Veiled Stair'),
(4, 'The Wandering Isle'),
(4, 'Timeless Isle'),
(4, 'Tol Barad'),
(4, 'Townlong Steppes'),
(4, 'Twilight Highlands'),
(4, 'Uldum'),
(4, 'Val''sharah'),
(4, 'Vale of Eternal Blossoms'),
(4, 'Valley of the Four Winds'),
-- Mixed Vanilla/Cata START COPY PASTE
(4, 'Ashenvale'),
(4, 'Arathi Highlands'),
(4, 'Azshara'),
(4, 'Badlands'),
(4, 'Blasted Lands'),
(4, 'Burning Steppes'),
(4, 'Darkshore'),
(4, 'Darnassus'),
(4, 'Deadwind Pass'),
(4, 'Desolace'),
(4, 'Dun Morogh'),
(4, 'Durotar'),
(4, 'Duskwood'),
(4, 'Dustwallow Marsh'),
(4, 'Eastern Plaguelands'),
(4, 'Elwynn Forest'),
(4, 'Felwood'),
(4, 'Feralas'),
(4, 'Hillsbrad Foothills'),
(4, 'Loch Modan'),
(4, 'Moonglade'),
(4, 'Mulgore'),
(4, 'Redridge Mountains'),
(4, 'Searing Gorge'),
(4, 'Silithus'),
(4, 'Silverpine Forest'),
(4, 'Stonetalon Mountains'),
(4, 'Stormwind City'),
(4, 'Stranglethorn Vale'),
(4, 'Swamp of Sorrows'),
(4, 'Tanaris'),
(4, 'Teldrassil'),
(4, 'Thousand Needles'),
(4, 'Tirisfal Glades'),
(4, 'Wetlands'),
(4, 'Western Plaguelands'),
(4, 'Westfall'),
(4, 'Winterspring'),
(4, 'Un''goro Crater'),
-- END COPY PASTE
-- WoD
(5, 'Ashran'),
(5, 'Frostfire Ridge'),
(5, 'Gorgrond'),
(5, 'Nagrand'),
(5, 'Shadowmoon Valley'),
(5, 'Spires of Arak'),
(5, 'Talador'),
(5, 'Tanaan Jungle'),
-- BfA
(6, 'Boralus'),
(6, 'Dazar''Alor'),
(6, 'Drustvar'),
(6, 'Mechagon'),
(6, 'Nazjatar'),
(6, 'Nazmir'),
(6, 'Stormsong Valley'),
(6, 'Tiragarde Sound'),
(6, 'Vol''dun'),
(6, 'Zuldazar');
